[package]
name = "rust-microservice-server"
version = "0.1.0"
authors = ["Marcus Johansson <mjoh9512@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
rocket="0.4.5"
shiplift="0.6.0"
=======
>>>>>>> 7a6736e8d47810000262ec341d213a5a88afeecf
